routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('empleats', App\Http\Controllers\EmpleatController::class);

Route::resource('productes', App\Http\Controllers\ProducteController::class);

app/Models/Empleat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Empleat extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'due',
        'comments'
    ];
}

app/Models/Producte.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Producte extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'category',
        'description'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmpleatController.php
<?php

namespace App\Http\Controllers;

use App\Models\Empleat;
use Illuminate\Http\Request;

class EmpleatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $empleats = Empleat::Paginate(5);
        return view('empleat.index')
            ->with('empleats', $empleats);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('empleat.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:15',
            'due' => 'required|gte:50'
        ]);

        $empleat = Empleat::create($request->only('name', 'due', 'comments'));

        return redirect()->route('empleats.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Empleat  $empleat
     * @return \Illuminate\Http\Response
     */
    public function show(Empleat $empleat)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Empleat  $empleat
     * @return \Illuminate\Http\Response
     */
    public function edit(Empleat $empleat)
    {
        return view('empleat.form')
            ->with('empleat', $empleat);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Empleat  $empleat
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Empleat $empleat)
    {
        $request->validate([
            'name' => 'required|max:15',
            'due' => 'required|gte:50'
        ]);

        $empleat->name = $request['name'];
        $empleat->due = $request['due'];
        $empleat->comments = $request['comments'];
        $empleat->save();

        return redirect()->route('empleats.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Empleat  $empleat
     * @return \Illuminate\Http\Response
     */
    public function destroy(Empleat $empleat)
    {
        $empleat->delete();
        return redirect()->route('empleats.index');
    }
}

app/Http/Controllers/ProducteController.php
<?php

namespace App\Http\Controllers;

use App\Models\Producte;
use Illuminate\Http\Request;

class ProducteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $productes = Producte::Paginate(10);
        return view('producte.index')
            ->with('productes', $productes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('producte.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:15',
        ]);

        $producte = Producte::create($request->only('name', 'category', 'description'));

        return redirect()->route('productes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Producte  $producte
     * @return \Illuminate\Http\Response
     */
    public function show(Producte $producte)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Producte  $producte
     * @return \Illuminate\Http\Response
     */
    public function edit(Producte $producte)
    {
        return view('producte.form')
            ->with('producte', $producte);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Producte  $producte
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Producte $producte)
    {
        $request->validate([
            'name' => 'required|max:15',
        ]);

        $producte->name = $request['name'];
        $producte->category = $request['category'];
        $producte->description = $request['description'];
        $producte->save();

        return redirect()->route('productes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Producte  $producte
     * @return \Illuminate\Http\Response
     */
    public function destroy(Producte $producte)
    {
        $producte->delete();
        return redirect()->route('productes.index');
    }
}

resources/views/empleat/form.blade.php
@extends('theme/base')
@section('contingut')
<div class="container py-5 text-center">

   @if (isset($empleat))
   <h1>Editar empleat</h1>
   @else
   <h1>Crear empleats</h1>
   @endif

   @if (isset($empleat))
   <form action="{{ route('empleats.update', $empleat)}}" method="post">
      @method('PUT')
   @else
   <form action="{{ route('empleats.store')}}" method="post">
   @endif

   @csrf
   <div class="mb-3">
        <label for="name" class="form-label">Nom</label>
        <input type="text" name="name" class="form-control" placeholder="Nom de l'empleat" value="{{old('name') ?? @$empleat->name}}">
        @error('name')
           <p class="form-text text-danger">{{$message}}</p>
        @enderror
   </div>
   <div class="mb-3">
        <label for="due" class="form-label">Salari</label>
        <input type="number" name="due" class="form-control" placeholder="Salari de l'empleat" value="{{old('due') ?? @$empleat->due}}" step="0,01">
        @error('due')
           <p class="form-text text-danger">{{$message}}</p>
        @enderror
   </div>
   <div class="mb-3">
        <label for="comments" class="form-label">Comentaris</label>
        <textarea type="text" name="comments" class="form-control" placeholder="Observacions del empleat">{{old('comments') ?? @$empleat->comments}}</textarea>
        @error('comments')
           <p class="form-text text-danger">{{$message}}</p>
        @enderror  
   </div>

   @if (isset($empleat))
   <button type="submit" class="btn btn-info">Editar Empleat</button>
   @else
   <button type="submit" class="btn btn-info">Desar Empleat</button>
   @endif
</form>
</div>
  
@endsection

resources/views/empleat/index.blade.php
@extends('theme/base')
<body>
    @section('contingut')
    <div class="container py-5 text-center">
        <h1>Llistat d'empleats</h1>
        <a href="{{ route('empleats.create')}}" class="btn btn-primary">Crear Empleats</a>
    </div>
    <table class="table">
        <thead class="thead-dark">
            <tr>
            <th scope="col">Nom</th>
            <th scope="col">Sueldo</th>
            <th scope="col">Accions</th>
            </tr>
        </thead>
        <tbody>
            @forelse($empleats as $empleat)
            <tr>
                <td>{{ $empleat->name }}</td>
                <td>{{ $empleat->due}}</td>
                <td><a href="{{route('empleats.edit', $empleat)}}" class="btn btn-warning">Editar</a>
                    <form action="{{route('empleats.destroy', $empleat)}}" method="post" class="d-inline">
                        @method('DELETE')
                        @csrf
                        <button type="submit" class="btn btn-danger" onclick="return confirm('¿Estas seguro?')">Eliminar</button>
                    </form>
                </td>
            </tr>
            @empty
                <td colspan="3">Actualmente no hi ha registres</td>
            @endforelse
        </tbody>
        </table>
        <div style="margin-left: 47%;">
            {{ $empleats->links("pagination::bootstrap-4") }}
        </div>
    @stop
</body>

resources/views/producte/form.blade.php
@extends('theme/base')
@section('contingut')
<div class="container py-5 text-center">

   @if (isset($producte))
   <h1>Editar producte</h1>
   @else
   <h1>Crear productes</h1>
   @endif

   @if (isset($producte))
   <form action="{{ route('productes.update', $producte)}}" method="post">
      @method('PUT')
   @else
   <form action="{{ route('productes.store')}}" method="post">
   @endif

   @csrf
   <div class="mb-3">
        <label for="name" class="form-label">Nom</label>
        <input type="text" name="name" class="form-control" placeholder="Nom de l'producte" value="{{old('name') ?? @$producte->name}}">
        @error('name')
           <p class="form-text text-danger">{{$message}}</p>
        @enderror
   </div>
   <div class="mb-3">
        <label for="category" class="form-label">Categoria</label>
        <select name="category" id="category" class="custom-select">
            <option value="Fruta" @if (old('category') == "Fruta") {{ 'selected' }} @endif>Fruta</option>
            <option value="Verdura" @if (old('category') == "Verdura") {{ 'selected' }} @endif >Verdura</option>
            <option value="Carne" @if (old('category') == "Carne") {{ 'selected' }} @endif>Carne</option>
            <option value="Pescado" @if (old('category') == "Pescado") {{ 'selected' }} @endif >Pescado</option>
        </select>
        <!-- <input type="text" name="category" class="form-control" placeholder="Categoria de l'producte" value="{{old('category') ?? @$producte->category}}" step="0,01"> -->
        @error('category')
           <p class="form-text text-danger">{{$message}}</p>
        @enderror
   </div>
   <div class="mb-3">
        <label for="description" class="form-label">Descripcion</label>
        <textarea type="text" name="description" class="form-control" placeholder="Descripcion del producte">{{old('description') ?? @$producte->description}}</textarea>
        @error('description')
           <p class="form-text text-danger">{{$message}}</p>
        @enderror  
   </div>

   @if (isset($producte))
   <button type="submit" class="btn btn-info">Editar producte</button>
   @else
   <button type="submit" class="btn btn-info">Desar producte</button>
   @endif
</form>
</div>
  
@endsection

resources/views/producte/index.blade.php
@extends('theme/base')

<body>
    @section('contingut')
    <div class="container py-5 text-center">
        <h1>Llistat d'productes</h1>
        <a href="{{ route('productes.create')}}" class="btn btn-primary">Crear Productes</a>
    </div>
    <table id="table" class="table">
        <thead class="thead-dark">
            <tr>
                <th style="cursor: pointer;" onclick="sortTable(0)" scope="col">Nom</th>
                <th style="cursor: pointer;" onclick="sortTable(1)" scope="col">Categoria</th>
                <th scope="col">Accions</th>
            </tr>
        </thead>
        <tbody>
            @forelse($productes as $producte)
            <tr>
                <td>{{ $producte->name }}</td>
                <td>{{ $producte->category}}</td>
                <td><a href="{{route('productes.edit', $producte)}}" class="btn btn-warning">Editar</a>
                    <form action="{{route('productes.destroy', $producte)}}" method="post" class="d-inline">
                        @method('DELETE')
                        @csrf
                        <button type="submit" class="btn btn-danger" onclick="return confirm('¿Estas seguro?')">Eliminar</button>
                    </form>
                </td>
            </tr>
            @empty
            <td colspan="3">Actualmente no hi ha registres</td>
            @endforelse
        </tbody>
    </table>
    <div style="margin-left: 47%;">
        {{ $productes->links("pagination::bootstrap-4") }}
    </div>
    <script>
        function sortTable(n) {
            var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
            table = document.getElementById("table");
            switching = true;
            dir = "asc";
            while (switching) {
                switching = false;
                rows = table.rows;
                for (i = 1; i < (rows.length - 1); i++) {
                    shouldSwitch = false;
                    x = rows[i].getElementsByTagName("TD")[n];
                    y = rows[i + 1].getElementsByTagName("TD")[n];
                    if (dir == "asc") {
                        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                            shouldSwitch = true;
                            break;
                        }
                    } else if (dir == "desc") {
                        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                            shouldSwitch = true;
                            break;
                        }
                    }
                }
                if (shouldSwitch) {
                    rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                    switching = true;
                    switchcount++;
                } else {
                    if (switchcount == 0 && dir == "asc") {
                        dir = "desc";
                        switching = true;
                    }
                }
            }
        }
        // Referencia: https://www.w3schools.com/howto/howto_js_sort_table.asp
    </script>
    @stop
</body>

resources/views/theme/base.blade.php
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{{ asset('css/header.css') }}">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <title>Daniel Romero</title>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <a class="navbar-brand" href="/"><img style="width: 300px;" src="https://www.mercadona.com/estaticos/images/mercadona_logo/es/mercadona-imagotipo-color-300.png"></a>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/empleats">Empleados</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="/productes">Productos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Ofertas</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  @yield('contingut')
  <footer class="bg-dark text-center text-white welcome-footer" >
    <div class="container p-4">
      <section class="mb-4">
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-facebook-f"></i></a>

        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-twitter"></i></a>

        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-google"></i></a>

        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-instagram"></i></a>

        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-linkedin-in"></i></a>

        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-github"></i></a>
      </section>

      <section class="mb-4">
        <p>
          Solo quiero el money
          Donde esté el cash
          There you find me
          Esperar cobrar, do you feel me?
          Yo quiero Lomba y no Pimkie
        </p>
        <a href="https://www.google.com/search?q=lyrics+cancion+mercadona&oq=lyrics+cancion+mercadona&aqs=chrome..69i57j0i22i30l3.3534j0j7&sourceid=chrome&ie=UTF-8">Leer Mas</a>
      </section>
    </div>
  </footer>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</html>